Version: 1.0

# ROS related paramaters
TopicQueue: 10

# Robot-Connection related parameters
RobotPort: 9559
RobotIP: 10.0.160.252
DriverBrokerPort: 54000
DriverBrokerIP: 0.0.0.0

# Communication related parameters
# 100Hz are perfect for Webots, 5-10Hz works ok on a real robot
ControllerFrequency: 12

# Robot related parameters
JointPrecision: 0.09
OdomFrame: odom
